services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/docker/Dockerfile.backend
    container_name: medgestor-app-backend-1
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      db_test:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - DB_NAME_TEST=medgestor_test
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST_TEST=db_test
      - DB_PORT_TEST=5432
      - SEED_DEFAULT_PASSWORD=pass123
      - JWT_SECRET=pBXlIutbAqH8liW667abZxQnoNkvKMRJTGfRu5X6sfA=
    networks:
      - medgestor-network
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/docker/Dockerfile.frontend
    container_name: medgestor-app-frontend-1
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - medgestor-network
    restart: unless-stopped
  db:
    image: postgres:17
    container_name: medgestor-app-db-1
    environment:
      - POSTGRES_DB=medgestor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - medgestor-network
    restart: unless-stopped
  db_test:
    image: postgres:17
    container_name: medgestor-app-db_test-1
    environment:
      - POSTGRES_DB=medgestor_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - medgestor-network
    restart: unless-stopped
networks:
  medgestor-network:
    driver: bridge
volumes:
  db_data: